name: Release Build

on:
  push:
    tags:
      - 'v*' # Trigger only when pushing a tag starting with "v"

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (Release)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.SECRET_TOKEN }}
          allowUpdates: true

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable macOS Desktop
        run: flutter config --enable-macos-desktop

      - name: Build macOS (Release)
        run: flutter build macos --release

      - name: Upload macOS build to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/macos/Build/Products/Release/*.app"
          token: ${{ secrets.SECRET_TOKEN }}
          allowUpdates: true

  build-linux:
    name: Build Linux App
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux build dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Linux Desktop
        run: flutter config --enable-linux-desktop

      - name: Build Linux (Release)
        run: flutter build linux --release

      - name: Upload Linux build to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/linux/x64/release/bundle/*"
          token: ${{ secrets.SECRET_TOKEN }}
          allowUpdates: true
